name: Android Build

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
        
      - name: Set Up Jdk
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build Project
        run: ./gradlew assembleDebug

       -name: Upload APK
        uses: actions/upload-artifacts@v2
        with:
          name: apk
          path: app/build/outputs/apk/debug/**.apk



